import 'package:get/get.dart';

class AppLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'home': "Home",
          'report': "Report",
          'settings': "Settings",
          'about_app': "About App",
          'app_info': "HiKi - Hisob Kitob (Financial Records)",
          'app_description':
              "This expense tracking app helps you manage your income and expenses. Analyze your spending, view reports, and control your budget.",
          'developer': "Developer",
          'developer_info':
              "Developer - Usmonov Dovudjon\nA passionate Flutter developer dedicated to creating innovative applications that make daily tasks easier and more efficient.",
          'features': "Features",
          'feature_1': "Track income and expenses",
          'feature_2': "View daily, weekly, monthly, and yearly reports",
          'feature_3': "Detailed reports and analysis",
          'feature_4': "Customizable categories",
          'feature_5': "Secure data storage",
          'contact': "Contact",
          'email_copied': "Email copied!",
          'version': "Version",
          'title': "Daily Expenses",
          'dark_mode': "Dark Mode",
          'language': "Language",
          'select_language': "Select App Language",
          'delete_all': "Delete All Entries",
          'delete_all_desc':
              "Completely erase all income and expenses entered so far",
          'about': "About App",
          'about_desc': "Learn more about this application",
          'switch_language': "Switch Language",
          'income_name': "Income title",
          'expense_name': "Expense title",
          'amount': "Amount",
          'select_date': "Select Date",
          'transactions_count': "Number of Transactions",
          'income': "Income",
          'expense': "Expense",
          'cancel': "Cancel",
          'save': "Save",
          'category': "Category",
          'number_of_transactions': "Number of Transactions",
          'select_category': "Select Category",
          'overall_period': "Overall",
          'today_period': "Today",
          'week_period': "This week",
          'month_period': "This Month",
          'year_period': "This year",
          'report_title': "Report",
          'total_income': "Total Income",
          'total_expense': "Total Expense",
          'chart_title': "Chart",
          'bucket_amount': "Amount",
          'current_balance': "Current Balance",
          'no_data_message':
              "No data available currently. Please add new income or expense!",
          'loading': "Loading...",
          'delete': "Delete",
          'date_not_entered': "Date not entered",
          'som': "Som",
          'change_currency': 'Change currency',
          'remember_delete_action':
              "Remember, by performing this action, you will delete all income and expenses, and it will not be possible to recover them!!!",
          'warning': "Notification",
          'please_enter_valid':
              "Please enter a valid title, amount, date, and category.",
          'confirm': "Confirm",
          'deleting_all': "Delete all items?",
          'all_data_deleted': "All data has been deleted",
          'data_deleted': "Data deleted",
          'restore_message': "Do you want to restore?",
          'restore': "Restore",
          'total_profit': "Current Period Profit",
          'food': "Food",
          'transport': "Transport",
          'shopping': "Shopping",
          'utilities': "Utilities",
          'education': "Education",
          'work': "Work",
          'doctor': "Doctor",
          'personal': "Personal",
          'salary': "Salary",
          'investment': "Investment",
          'gift': "Gift",
          'service': "Service",
          'rent': "Rent",
          'business': "Business",
          'trade': "Trade",
          'reward': "Reward",
          'debts': "Debts",
          'travel': "Travel",
          'sport': "Sport",
          'payback': "Payback",
          'pension': "Pension",
          'savings': "Savings",
          'others': "Others",
          'swipe_to_remove': "Swipe left to remove me",
          'buying_groceries': "Buying groceries",
          'electricity': "Electricity",
          'selected': "Selected",
          'choose_language': "Choose Language",
          'continue': 'Continue',
          "update_available": "Update Available",
          "new_version_available":
              "A new version is available. Please update the app.",
          "later": "Later",
          "update_now": "Update Now",
          "restart_prompt":
              "The app needs to restart for the update to take effect.",
          "currency_change_note":
              "NOTE: The new currency will apply to all past transactions as well.",
          'confirm_delete': "Confirm Delete",
          'delete_message': "Are you sure you want to delete this item?",
          'edit': 'Edit',
          'error': 'Error',
          'please_enter_number_above': 'Please enter a number above',
          'succesfully_updated': "Successfully updated!",
          'app_will_close_reopen': "App will be closed now. Please reopen it.",
          'ok': "OK",
          "update_prompt":
              "It doesn't effect your data, only new features will be added or issues will be fixed."
        },
        'uz': {
          'home': "Asosiy",
          'report': "Hisobot",
          'settings': "Sozlash",
          'about_app': "Ilova haqida",
          'app_info': "HiKi - Hisob Kitob",
          'app_description':
              "Ushbu xarajatlarni kuzatuvchi ilova sizga daromad va xarajatlaringizni boshqarishda yordam beradi. Xarajatlaringizni tahlil qiling, hisobotlarni ko'ring va byudjetni nazorat qiling.",
          'developer': "Dasturchi",
          'developer_info':
              "Dasturchi - Usmonov Dovudjon\nFoydalanuvchilarni kundalik ishlarini osonlashtirishga va samarali boshqarishga yordam beradigan innovatsion ilovalarni yaratishga ishtiyoqmand flutter dasturchisi",
          'features': "Xususiyatlar",
          'feature_1': "Daromad va xarajatlarni kuzatib borish",
          'feature_2': "Kunlik, haftalik, oylik va yillik hisobotlarni ko'rish",
          'feature_3': "Batafsil hisobot va tahlil",
          'feature_4': "Moslashtiriladigan kategoriyalar",
          'feature_5': "Ma'lumotlarning xavfsiz saqlanishi",
          'contact': "Aloqa",
          'email_copied': "Elektron pochta nusxalandi!",
          'version': "Versiya",
          'title': "Kunlik xarajatlar",
          'dark_mode': "Tungi rejim",
          'language': "Til",
          'select_language': "Ilova tilini tanlang",
          'delete_all': "Barcha kiritmalarni o'chirish",
          'delete_all_desc':
              "Shu kungacha kiritilgan barcha kirim va chiqimlarni butunlay tozalab tashlash",
          'about': "Ilova haqida",
          'about_desc': "Ushbu ilova haqida ko'proq bilib oling",
          'switch_language': "Tilni almashtirish",
          'income_name': "Kirim nomi",
          'expense_name': "Chiqim nomi",
          'amount': "Miqdori",
          'select_date': "Sanani tanlang",
          'transactions_count': "Tranzaksiyalar soni",
          'income': "Kirim",
          'expense': "Chiqim",
          'cancel': "Bekor qilish",
          'save': "Saqlash",
          'category': "Kategoriya",
          'number_of_transactions': "Tranzaksiyalar soni",
          'select_category': "Kategoriya tanlang",
          'overall_period': "Umumiy",
          'today_period': "Bugun",
          'week_period': "Bu hafta",
          'month_period': "Bu oy",
          'year_period': "Bu yil",
          'report_title': "Hisobot",
          'total_income': "Jami daromad",
          'total_expense': "Jami xarajat",
          'chart_title': "Diagramma",
          'bucket_amount': "Miqdor",
          'current_balance': "Hozirgi Balans",
          'no_data_message':
              "Hozirda ma'lumotlar mavjud emas. Iltimos, yangi daromad yoki chiqim kiriting!",
          'loading': "Yuklanmoqda...",
          'delete': "O'chirish",
          'date_not_entered': "Sana kiritilmagan",
          'som': "So'm",
          'change_currency': "Pul birligini o'zgartirish",
          'remember_delete_action':
              "Eslatib o'tamizki, bu amalni bajarish orqali siz barcha kirim va chiqimlarni o'chirib tashlaysiz va ularni qayta tiklashni iloji yo'q !!!",
          'warning': "Ogohlantirish",
          'please_enter_valid':
              "Iltimos, to'g'ri nom, miqdor, sana va kategoriyani kiriting.",
          'confirm': "Tasdiqlash",
          'deleting_all': "Barchasini o'chirish!",
          'all_data_deleted': "Barcha ma'lumotlar o'chirildi",
          'data_deleted': "Ma'lumot o'chirildi",
          'restore_message': "Qayta tiklashni istaysizmi?",
          'restore': "Qayta tiklash",
          'total_profit': "Daromad",
          'food': "Taom",
          'transport': "Transport",
          'shopping': "Xaridlar",
          'utilities': "Kommunal",
          'education': "Bilim",
          'work': "Ish",
          'doctor': "Shifokor",
          'personal': "Shaxsiy",
          'salary': "Maosh",
          'investment': "Investitsiya",
          'gift': "Hadiya",
          'service': "Servis",
          'rent': "Ijara",
          'business': "Biznes",
          'trade': "Savdo",
          'reward': "Mukofot",
          'debts': "Qarz olish",
          'travel': "Sayohat",
          'sport': "Sport",
          'payback': "Qarz to'lovi",
          'pension': "Pensiya",
          'savings': "Jamg'arma",
          'others': "Boshqalar",
          'swipe_to_remove':
              "Quyidagi namuna ro'yhatlarni o'chirish uchun chapga suring",
          'buying_groceries': "Oziq-ovqat xaridlari",
          'electricity': "Elektr energiyasi",
          'selected': "Tanlandi",
          'choose_language': "Tilni tanlang",
          'continue': "Davom etish",
          "update_available": "Yangi versiya mavjud",
          "new_version_available":
              "Ilovaning yangi versiyasi mavjud. Iltimos, yangilang.",
          "later": "Keyinroq",
          "update_now": "Hozir yangilash",
          "restart_prompt":
              "Yangilanishni qo'llash uchun ilova qayta ishga tushirilishi kerak.",
          "currency_change_note":
              "ESLATMA: Yangi valyuta barcha oldingi tranzaksiyalarga ham tatbiq etiladi.",
          'confirm_delete': "O‘chirishni tasdiqlang",
          'delete_message': "Bu elementni o‘chirishga ishonchingiz komilmi?",
          'edit': 'Tahrirlash',
          'error': 'Xatolik',
          'please_enter_number_above': 'Yuqoridagi raqamni kiriting',
          'succesfully_updated': "Muvaffaqiyatli yangilandi!",
          'app_will_close_reopen': "Ilova yopiladi. Iltimos, uni qayta oching.",
          'ok': "OK",
          "update_prompt":
              "Bu ma'lumotlaringizga ta'sir qilmaydi, faqat yangi imkoniyatlar qo'shiladi yoki kamchiliklar to'g'irlanadi."
        },
        'kr': {
          'home': "홈",
          'report': "보고서",
          'settings': "설정",
          'about_app': "앱 정보",
          'app_info': "HiKi - Hisob Kitob (가계부)",
          'app_description':
              "이 지출 추적 앱은 수입과 지출을 관리하는 데 도움을 줍니다. 소비를 분석하고, 보고서를 확인하며, 예산을 조절하세요.",
          'developer': "개발자",
          'developer_info':
              "개발자 - 우스모노프 도부드존\n일상적인 작업을 더 쉽고 효율적으로 만드는 혁신적인 애플리케이션을 개발하는 열정적인 Flutter 개발자입니다.",
          'features': "기능",
          'feature_1': "수입 및 지출 추적",
          'feature_2': "일별, 주별, 월별, 연도별 보고서 확인",
          'feature_3': "상세한 보고서 및 분석",
          'feature_4': "맞춤형 카테고리 설정",
          'feature_5': "안전한 데이터 저장",
          'contact': "연락처",
          'email_copied': "이메일이 복사되었습니다!",
          'version': "버전",
          'title': "일일 지출",
          'dark_mode': "다크 모드",
          'language': "언어",
          'select_language': "앱 언어 선택",
          'delete_all': "모든 항목 삭제",
          'delete_all_desc': "지금까지 입력된 모든 수입 및 지출 데이터를 완전히 삭제합니다.",
          'about': "앱 정보",
          'about_desc': "이 애플리케이션에 대해 자세히 알아보세요.",
          'switch_language': "언어 변경",
          'income_name': "수입 제목",
          'expense_name': "지출 제목",
          'amount': "금액",
          'select_date': "날짜 선택",
          'transactions_count': "거래 횟수",
          'income': "수입",
          'expense': "지출",
          'cancel': "취소",
          'save': "저장",
          'category': "카테고리",
          'number_of_transactions': "거래 횟수",
          'select_category': "카테고리 선택",
          'overall_period': "전체",
          'today_period': "오늘",
          'week_period': "이번 주",
          'month_period': "이번 달",
          'year_period': "올해",
          'report_title': "보고서",
          'total_income': "총 수입",
          'total_expense': "총 지출",
          'chart_title': "차트",
          'bucket_amount': "금액",
          'current_balance': "현재 잔액",
          'no_data_message': "현재 데이터가 없습니다. 새로운 수입 또는 지출을 추가하세요!",
          'loading': "로딩 중...",
          'delete': "삭제",
          'date_not_entered': "날짜가 입력되지 않았습니다.",
          'som': "숨",
          'change_currency': "통화 변경",
          'remember_delete_action':
              "이 작업을 수행하면 모든 수입 및 지출 데이터가 삭제되며 복구할 수 없습니다!!!",
          'warning': "알림",
          'please_enter_valid': "올바른 제목, 금액, 날짜 및 카테고리를 입력하세요.",
          'confirm': "확인",
          'deleting_all': "모든 항목을 삭제하시겠습니까?",
          'all_data_deleted': "모든 데이터가 삭제되었습니다.",
          'data_deleted': "데이터가 삭제되었습니다.",
          'restore_message': "복원하시겠습니까?",
          'restore': "복원",
          'total_profit': "현재 기간 수익",
          'food': "음식",
          'transport': "교통",
          'shopping': "쇼핑",
          'utilities': "공과금",
          'education': "교육",
          'work': "근무",
          'doctor': "병원",
          'personal': "개인",
          'salary': "급여",
          'investment': "투자",
          'gift': "선물",
          'service': "서비스",
          'rent': "임대",
          'business': "사업",
          'trade': "거래",
          'reward': "보상",
          'debts': "빚들",
          'travel': "여행",
          'sport': "스포츠",
          'payback': "빚 갚기",
          'pension': "연금",
          'savings': "저축",
          'others': "기타",
          'swipe_to_remove': "왼쪽으로 밀어서 삭제",
          'buying_groceries': "식료품 구입",
          'electricity': "전기",
          'selected': "선택됨",
          'choose_language': "언어 선택",
          'continue': '계속하기',
          "update_available": "업데이트 가능",
          "new_version_available": "새로운 버전이 있습니다. 앱을 업데이트하세요.",
          "later": "나중에",
          "update_now": "지금 업데이트",
          "restart_prompt": "업데이트를 적용하려면 앱을 재시작해야 합니다.",
          "currency_change_note": "참고: 새로운 통화가 이전 모든 거래에도 적용됩니다.",
          'confirm_delete': "삭제 확인",
          'delete_message': "이 항목을 삭제하시겠습니까?",
          'edit': '편집',
          'error': '오류',
          'please_enter_number_above': '위의 숫자를 입력하세요',
          "update_prompt": "이는 데이터에 영향을 주지 않으며, 새로운 기능이 추가되거나 문제가 수정됩니다.",
        },
        'ru': {
          'home': "Главная",
          'report': "Отчёт",
          'settings': "Настройки",
          'about_app': "O приложении",
          'app_info': "Hisob Kitob (Учёт)",
          'app_description':
              "Это приложение для отслеживания расходов помогает вам управлять доходами и расходами. Анализируйте свои траты, просматривайте отчёты и контролируйте бюджет.",
          'developer': "Разработчик",
          'developer_info':
              "Разработчик - Усмонов Давуджон\nYвлeчённый Flutter-разработчик, посвящённый созданию инновационных приложений, упрощающих повседневные задачи.",
          'features': "Функции",
          'feature_1': "Отслеживание доходов и расходов",
          'feature_2': "Просмотр отчётов за день, неделю, месяц и год",
          'feature_3': "Детализированные отчёты и анализ",
          'feature_4': "Настраиваемые категории",
          'feature_5': "Безопасное хранение данных",
          'contact': "Контакты",
          'email_copied': "Электронная почта скопирована!",
          'version': "Версия",
          'title': "Ежедневные расходы",
          'dark_mode': "Тёмный режим",
          'language': "Язык",
          'select_language': "Выберите язык приложения",
          'delete_all': "Удалить все записи",
          'delete_all_desc': "Полностью удалить все внесённые доходы и расходы",
          'about': "O приложении",
          'about_desc': "Подробнее oб этом приложении",
          'switch_language': "Сменить язык",
          'income_name': "Название дохода",
          'expense_name': "Название расхода",
          'amount': "Сумма",
          'select_date': "Выберите дату",
          'transactions_count': "Количество транзакций",
          'income': "Доход",
          'expense': "Расход",
          'cancel': "Отмена",
          'save': "Сохранить",
          'category': "Категория",
          'number_of_transactions': "Количество транзакций",
          'select_category': "Выберите категорию",
          'overall_period': "Общий период",
          'today_period': "Сегодня",
          'week_period': "Эта неделя",
          'month_period': "Этот месяц",
          'year_period': "Этот год",
          'report_title': "Отчёт",
          'total_income': "Общий доход",
          'total_expense': "Общий расход",
          'chart_title': "График",
          'bucket_amount': "Сумма",
          'current_balance': "Текущий баланс",
          'no_data_message':
              "Данных пока нет. Пожалуйста, добавьте новый доход или расход!",
          'loading': "Загрузка...",
          'delete': "Удалить",
          'date_not_entered': "Дата не введена",
          'som': "сум",
          'change_currency': "Сменить валюту",
          'remember_delete_action':
              "Помните, что при выполнении этого действия все доходы и расходы будут удалены, и их невозможно будет восстановить!!!",
          'warning': "Уведомление",
          'please_enter_valid':
              "Пожалуйста, введите корректное название, сумму, дату и категорию.",
          'confirm': "Подтвердить",
          'deleting_all': "Удалить все записи?",
          'all_data_deleted': "Bce данные удалены",
          'data_deleted': "Данные удалены",
          'restore_message': "Хотите восстановить?",
          'restore': "Восстановить",
          'total_profit': "Прибыль за текущий период",
          'food': "Еда",
          'transport': "Транспорт",
          'shopping': "Покупки",
          'utilities': "Коммунальные услуги",
          'education': "Образование",
          'work': "Работа",
          'doctor': "Доктор",
          'personal': "Личное",
          'salary': "Зарплата",
          'investment': "Инвестиции",
          'gift': "Подарок",
          'service': "Услуга",
          'rent': "Аренда",
          'business': "Бизнес",
          'trade': "Торговля",
          'reward': "Вознаграждение",
          'debts': "Долги",
          'travel': "Путешествие",
          'sport': "Спорт",
          'payback': "Оплата долга",
          'pension': "Пенсия",
          'savings': "Сбережения",
          'others': "Другое",
          'swipe_to_remove': "Смахните влево, чтобы удалить",
          'buying_groceries': "Покупка продуктов",
          'electricity': "Электроэнергия",
          'selected': "Выбрано",
          'choose_language': "Выберите язык",
          'continue': "Продолжить",
          "update_available": "Доступно обновление",
          "new_version_available":
              "Доступна новая версия приложения. Пожалуйста, обновите.",
          "later": "Позже",
          "update_now": "Обновить сейчас",
          "restart_prompt":
              "Для применения обновления необходимо перезапустить приложение.",
          "currency_change_note":
              "ПРИМЕЧАНИЕ: Новая валюта также будет применяться ко всем прошлым транзакциям.",
          'confirm_delete': "Подтвердить удаление",
          'delete_message': "Вы уверены, что хотите удалить этот элемент?",
          'edit': 'Редактировать',
          'error': 'Ошибка',
          'please_enter_number_above': 'Введите число выше',
          'succesfully_updated': "Успешно обновлено!",
          'app_will_close_reopen':
              "Приложение сейчас закроется. Пожалуйста, откройте его снова.",
          'ok': "OK",
          "update_prompt": "Это не повлияет на ваши данные, будут добавлены только новые функции или исправлены ошибки."
        },
      };
}
